apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: localrepo
  namespace: default
spec:
  url: http://172.17.0.1:8080
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.10.0"
      sourceRef:
        kind: HelmRepository
        name: localrepo
        namespace: default
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values # Kustomize handles the suffix matching
      valuesKey: values.yaml
