apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.3.5"
      sourceRef:
        kind: HelmRepository
        name: localrepo
        namespace: default
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values # Kustomize handles the suffix matching
      valuesKey: values.yaml
